NoConsoleOutput: false
DEBUG: false

# Illegal block preventions
PreventPlacingIllegalBlocks: true
RemoveIllegalBlockOnPlace: true
RemoveIllegalBlocksOnInteract: true
RemoveIllegalBlocksOnJoin: true
RemoveIllegalBlocksOnInventoryOpen: true
RemoveIllegalBlocksOnDrop: true
RemoveIllegalBlocksOnClick: true
RemoveIllegalBlocksOnPickup: true
RemoveIllegalBlocksOnMove: true
# Remove illegal blocks on chunkload, useful if players have placed a lot of bedrock/other blocks and you want to get rid of it
RemoveALLIllegalBlocksOnCHUNKLOAD: false
RevertStackedItems: true
# Check for items every X time may cause lag, disable if you have lag issues
StrictIllegalPrevention: false

# Bugfixes
PreventEndGatewayCrashExploit: true
PreventDestroyingEndPortals: true
FillInBedrockFloor: true
FillInBedrockRoof: true
PreventGoingBelowBedrockFloor: true
DisableAllElytras: false
DisableWithers: false
DisableExplosions: false
FixChatcoIgnoreBug: true
FixWorldStatsCommandBug: true
PreventGodMode: true
# Attempt to prevent chunk bans/fps lag.
PreventChunkBan: true
MaxEnchantmentTablePerChunk: 16
MaxEnderchestPerChunk: 16
MaxContainerPerChunk: 1000
MaxSignPerChunk: 100
# Antispam time in seconds
AntiSpamTime: 3
AntiSpamWordTime: 60

# Dupe preventions
DisableChestsOnDonkeys: false
PreventDonkeysFromGoingThroughPortals: false

# Other options
ChunksCommand: true
MaskKickMessages: false
PreventSpamKick: false
# Code by John200410, edited by moomoo
Preventlinks: false
Replace@: false
GrayJoinLeaveMessages: false
JoinMessage: "joined the game."
LeaveMessage: "left the game."
# COMMAND WHITELIST
# This will make it pretty much impossible to find your plugins as only the commands you specify will be able to work. Any other commands will show "Bad command. Type /help for all commands."
CommandWhitelist: false
AllowOPStobypass: true
CommandsWhitelisted:
  - /help
  - /msg
  - /kill
  - /discord
  - /togglechat
  - /toggletells
  - /ignore
  - /ignorelist
  - /toggledeathmsg
  - /stats
  - /tps
  - /w
  - /m
  - /t
  - /pm
  - /tell
  - /whisper
  - /r
  - /reply


# Specific Elytra speed settings for ONLY NEW and OLD chunks (set nocheatplus elytra settings to 999999)
# Disable by setting to 999999
ElytraOldChunkSpeed: 9 # max speed
ElytraNewChunkSpeed: 3.12 # 223km/h

# Patch futureclient boat fly exploit
# Note: this also prevents boats on land. Boats in water are fine
BoatflyPatch: true
# Enable the strict patch if you have players bypassing the normal patch please note this may use much more cpu as it checks every players location even if they aren't moving.
# Will also be a lot more buggy on land and won't support falling from high heights on a boat.
BoatflyPatchStrict: false
# How many ticks per second until every player is checked again
BoatflyPatchStrictCheckRate: 20L

# Send "Boatfly disabled due to an exploit >:) If you aren't boat flying, boats on land are a little buggy."
BoatflyMessage: true


# Show some info on the actionbar while flying with elytra.
ElytraActionBar: true

# List of banned blocks.
# WARNING: ADDING MOB SPAWNER TO THIS LIST WHILE HAVING RemoveALLIllegalBlocksOnCHUNKLOAD ENABLED WILL REMOVE ALL MOB SPAWNERS IN YOUR WORLD.
# You can also add non blocks and they should get removed aswell.
BANNED_BLOCKS:
  - BEDROCK
  - BARRIER
  - COMMAND
  - STRUCTURE_BLOCK
  - MONSTER_EGG

# The item banned blocks are replaced with.
Replacement_Item: STONE

# No need to mess with these they are meant for my server
# 1b1t options
AllowBreakingBedrock: false
1b1tPlaceBedrock: false
UseSparkhealth: false
nickresetonly: false
5000blocksawaytoteleport: false
SendClientInstructions: false
# This will only allow walking on the nether roof. Use permission node anarchyexploitfixes.netherroofbypass to bypass
PreventNetherRoof: false
# Enable the 1b1t slow! dupe - 5% chance of duplicating items by punching an item frame.
SlowDupe: false
# Enable /players, shows geared and non geared players. (if they have armor)
playercommand: false

DisableNCPGeyser: false
BypassSlots: false

# DISABLE STUFF AT CERTAIN TPS
# SET TO -1 TO DISABLE.
Redstone: 16

Elytra: 13
# Removes the elytra from the player's chestplate slot, there is no need to do this as this will make players fall to their death once tps is low.
RemoveElytra: false

Explosions: 17

FallingBlocks: 19