metadata.format.version = "1.1"

[versions]
runpaperversion = "1.20.4"
foliabundle = "1.20.4-R0.1-SNAPSHOT"

[libraries]
folia = "dev.folia:folia-api:1.20.4-R0.1-SNAPSHOT"
paper12 = "com.destroystokyo.paper:paper-api:1.12.2-R0.1-SNAPSHOT"
caffeineJ17 = "com.github.ben-manes.caffeine:caffeine:3.1.8"
caffeineJ8 = "com.github.ben-manes.caffeine:caffeine:2.9.3"
hikaricp = "com.zaxxer:HikariCP:5.1.0"
luckperms = "net.luckperms:api:5.4"

[plugins]
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.3.1" }
shadow = { id = "com.gradleup.shadow", version = "8.3.5" }
userdev = { id = "io.papermc.paperweight.userdev", version = "1.7.7" }
downgradeJava = { id = "xyz.wagyourtail.jvmdowngrader", version = "1.2.1" }

[bundles]
